# https://mqtt-io.app/2.2.6/#/config/scenarios
mqtt:
  host: 192.168.1.168
  port: 1883
  user: ""
  password: ""
  topic_prefix: "" # home/livingroom/sockets
  ha_discovery:
    enabled: yes

# GPIO
gpio_modules:
  # Use the Raspberry Pi built-in GPIO
  - name: rpi
    module: raspberrypi
# digital_inputs:
#   # Pin 0 is an input connected to a doorbell button
#   - name: doorbell
#     module: rpi
#     pin: 0

# digital_outputs:
#   # Pin 1 is an output connected to a light
#   - name: porch_light
#     module: rpi
#     pin: 1

# # Sensors
# sensor_modules:
#   # An LM75 sensor attached to the I2C bus
#   - name: lm75_sensor
#     module: lm75
#     i2c_bus_num: 1
#     chip_addr: 0x48

# sensor_inputs:
#   # The configuration of the specific sensor value to use (LM75 only has temperature)
#   - name: porch_temperature
#     module: lm75_sensor

# # Streams
# stream_modules:
#   # A serial port to communicate with the house alarm system
#   - name: alarm_system
#     module: serial
#     device: /dev/ttyUSB0
#     baud: 9600
