- platform: mqtt
  name: Zigbee2mqtt Networkmap
  # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
  state_topic: zigbee2mqtt/bridge/response/networkmap
  value_template: >-
    {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
  # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
  json_attributes_topic: zigbee2mqtt/bridge/response/networkmap
  json_attributes_template: "{{ value_json.data.value | tojson }}"
  # ################################
  # https://www.home-assistant.io/integrations/pyload
- platform: pyload
    #     Configuration Variables
    # Looking for your configuration file?
    # host string (Optional, default: localhost)

    # This is the IP address of your pyLoad download manager.
    # port integer (Optional, default: 8000)

    # The port your pyLoad interface uses.
    # name string (Optional, default: 20)

    # The name to use when displaying this pyLoad instance.
    # username string (Optional)

    # Your pyLoad username.
    # password string (Optional)

    # Your pyLoad password.
    # ssl boolean (Optional, default: false)

    # Enable SSL/TLS for the host.
- platform: websocket_api
- platform: pirateweather
  api_key: T1Nc6W2xe2b1wBMQ
  scan_interval: '01:00:00'
  monitored_conditions:
    - temperature
    - precip_probability
    - precip_type
    - humidity
    - cloud_cover
    - nearest_storm_distance
    - precip_intensity
    - wind_speed
